### ISSUE TITLE
Error Appears when I update electronic_protocol/www files from the "new" updated files

### ISSUE THREAD

**Issue by sarlisj** [g-theodoroy/electronic_protocol#8]
Fatal error: Declaration of App\Exceptions\Handler::report(Throwable $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Exception $e) in C:\Users\Dntis\ownCloud\electronic_protocol\www\app\Exceptions\Handler.php on line 8

**Comment by sarlisj** [comment]
When I replace Handler.php with the old one I get:

Fatal error: Uncaught RuntimeException: A facade root has not been set. in C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:234 Stack trace: #0 C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(397): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array) #1 C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(374): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #2 C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(289): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException)) #3 C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(188): Illuminate\Foundation\Exceptions\Handl in C:\Users\Dntis\ownCloud\electronic_protocol\www\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 234
